
[font]
size = 20

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "none"

[window.padding]
x = 7
y = 0

[keyboard]
bindings = [
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left", mods = "Alt", chars = "\u001BB" },
]

[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
