import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 22

[font.normal]
family = "Inconsolata Nerd Font"

[window]
decorations = "none"

[window.padding]
x = 7
y = 0

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
