import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.normal]
family = "MesloLGS Nerd Font Mono"
#family = "JetBrainsMono Nerd Font"

[window]
opacity = 0.85
blur = false

[window.padding]
x = 10
y = 10

[keyboard]
bindings = [
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left", mods = "Alt", chars = "\u001BB" },
]
